version: "2"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/root/src
      - gradle-cache:/root/.gradle:cached
    env_file:
      - .env

volumes:
  gradle-cache:
    driver: local

