/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ReactionBot

import kotlin.random.Random

import net.dv8tion.jda.api.JDA
import net.dv8tion.jda.api.JDABuilder
import net.dv8tion.jda.api.events.ReadyEvent
import net.dv8tion.jda.api.events.message.guild.GuildMessageReceivedEvent
import net.dv8tion.jda.api.hooks.ListenerAdapter
import net.dv8tion.jda.api.requests.GatewayIntent

class BotClient : ListenerAdapter(){
    lateinit var jda: JDA

    val commentOfMention = listOf("早よ来い", "ゲームするぞボケ", "Valorantしよ")

    fun main(token: String) { //トークンを使ってBotを起動する部分
        jda = JDABuilder.createLight(token,
            GatewayIntent.GUILD_MESSAGES)
            .addEventListeners(this)
            .build()
    }

    override fun onReady(event: ReadyEvent) { //Botがログインしたときの処理
        println("起動しました")
    }

    override fun onGuildMessageReceived(event : GuildMessageReceivedEvent) {
        val message = event.message;

        //Botがメッセージを受信したときの処理
        if(message.contentDisplay == "/neko"){//メッセージ内容を確認
            event.channel.sendMessageFormat("にゃーん").queue() //メッセージ送信
        }

        // メンションのみのメッセージがあった時の処理
        if(message.contentDisplay.startsWith("@")){
            val sendMessage = commentOfMention.get(Random.nextInt(commentOfMention.size))
            event.channel.sendMessageFormat(sendMessage).queue()
        }
    }
}

/*Kotlinではコード中から単体main関数を探して最初に実行します。
そこでmain関数にBotClientクラスのインスタンス作成とトークンを渡した起動処理mainメソッドを実行させる形でBotを起動します。
*/
fun main() {
    val bot = BotClient()
    bot.main(System.getenv("DISCORD_BOT_TOKEN"))
}